name: Keep HF Spaces Awake

on:
  # run every 12 hours
  schedule:
    - cron: '0 */12 * * *'

jobs:
  ping-spaces:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Spaces
        run: |
          set -e
          SPACES=(
            "https://hf.space/embed/Arkm20/player-api/+"
            "https://hf.space/embed/Arkm20/video-downloader/+"
            "https://hf.space/embed/Arkm20/authapi/+"
          )
          for url in "${SPACES[@]}"; do
            echo "Pinging $url"
            curl --max-time 10 -s "$url" || echo "  ⚠️ failed to reach $url"
          done